name: Sync Fork with Upstream

on:
  workflow_dispatch:  # allows manual run
  schedule:
    - cron: '0 2 * * *'  # every day at 2AM UTC

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/BelledonneCommunications/bcg729.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories --no-edit || echo "Nothing to merge"

      - name: Push changes to origin
        run: git push origin main
